title: Dr. Anand Pal
description: Associate Professor of Physics, Specializing in Quantum Technologies & Global Higher Education
url: "http://anandpal.in"
baseurl: "/Test-website-Anand"
permalink: pretty
markdown: kramdown
